### ISSUE TITLE
Build and run issues with npm install

### ISSUE THREAD

**Issue by maxruby** [johnpapa/a2-first-look#8]
After cloning the repo from here and typing `npm install`, I got the following fatal errors:

1.  typings script
```
> typings install
sh: typings: command not found
```
For now, I simply removed the references to this script within the npm script tag, though I am sure this is not the solution.

2. Application loading stuck on 404 due to incorrect path of `main.js`

Changing line 10 of `systemjs.config.js` from ` 'main': 'app/main.js',`to `'main': 'main.js',` fixed the problem. 

Please let me know whether there are quick fixes to these issues. 
Thanks.

**Comment by johnpapa** [comment]
i think you mean the package.json in the examples folder. that is not intended to be run to see the examples.

Refer to the readme for details, which explains which folders to look at.

**Comment by maxruby** [comment]
Not sure why this happened. I definitely had a problem the first time I cloned the repo and followed the steps you mentioned.  The error was directly related to the "typings" script which is indeed included in the `package.json`file inside the `_examples/storyline-tracker folder`. 

Thanks again for the explanation and a great course.
